// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqHO2je64xTNQJ2rKOL8kAEI4I6a4kuhQ',
    appId: '1:567759282811:web:6b79d69bbf093631c638de',
    messagingSenderId: '567759282811',
    projectId: 'fir-auth-and-crud-a5c94',
    authDomain: 'fir-auth-and-crud-a5c94.firebaseapp.com',
    storageBucket: 'fir-auth-and-crud-a5c94.appspot.com',
    measurementId: 'G-NE47Z7H3FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8nf-kCcscLnHphVwTR6EbADCtTvtTfw',
    appId: '1:567759282811:android:bbd3ce8fa17adbc4c638de',
    messagingSenderId: '567759282811',
    projectId: 'fir-auth-and-crud-a5c94',
    storageBucket: 'fir-auth-and-crud-a5c94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1a2V4ZJVCP5A5_7XlNvumwysoRlpEzs',
    appId: '1:567759282811:ios:b1dd59f73a9f455cc638de',
    messagingSenderId: '567759282811',
    projectId: 'fir-auth-and-crud-a5c94',
    storageBucket: 'fir-auth-and-crud-a5c94.appspot.com',
    iosClientId: '567759282811-25i5e61893j1e2hvfqdqj1d5ck07m1rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthCurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1a2V4ZJVCP5A5_7XlNvumwysoRlpEzs',
    appId: '1:567759282811:ios:b1dd59f73a9f455cc638de',
    messagingSenderId: '567759282811',
    projectId: 'fir-auth-and-crud-a5c94',
    storageBucket: 'fir-auth-and-crud-a5c94.appspot.com',
    iosClientId: '567759282811-25i5e61893j1e2hvfqdqj1d5ck07m1rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthCurd',
  );
}
